project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"

preserve_hierarchy: true

files:
  - source: '/app/src/main/res/values/strings.xml'
    translation: '/app/src/main/res/values-%android_code%/strings.xml'
    dest: '/Manager/strings.xml'
    skip_untranslated_strings: true

  - source: '/app/src/main/res/values/plurals.xml'
    translation: '/app/src/main/res/values-%android_code%/plurals.xml'
    dest: '/Manager/plurals.xml'
    skip_untranslated_strings: true
