{
  "formatVersion": "1.1",
  "component": {
    "group": "kofua.app.revanced",
    "module": "apktool-lib",
    "version": "2.12.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "kofua.app.revanced",
          "module": "brut.j.common",
          "version": {
            "requires": "2.12.0.1"
          }
        },
        {
          "group": "kofua.app.revanced",
          "module": "brut.j.util",
          "version": {
            "requires": "2.12.0.1"
          }
        },
        {
          "group": "kofua.app.revanced",
          "module": "brut.j.dir",
          "version": {
            "requires": "2.12.0.1"
          }
        },
        {
          "group": "kofua.app.revanced",
          "module": "brut.j.xml",
          "version": {
            "requires": "2.12.0.1"
          }
        },
        {
          "group": "kofua.app.revanced",
          "module": "brut.j.yaml",
          "version": {
            "requires": "2.12.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "apktool-lib-2.12.0.1.jar",
          "url": "apktool-lib-2.12.0.1.jar",
          "size": 34978779,
          "sha512": "a94bcdf55c44f8669fb72c73438d8045fb94976adda88c3413f234cd3d03d9a10303a3e9d28fa07cd17bd812f84c6651386537e18b573136301b581e95bf2abe",
          "sha256": "dc850340dc65cb1d213e470225bb64e60ff9c8cd59035d481809036b048eb87f",
          "sha1": "2bf0f1a36647822f6d6e6956b6428c4060a41792",
          "md5": "d25f010b6360c11f5bf20435f3696f97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.smali",
          "module": "smali-baksmali",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "com.android.tools.smali",
          "module": "smali",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.18.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "kofua.app.revanced",
          "module": "brut.j.common",
          "version": {
            "requires": "2.12.0.1"
          }
        },
        {
          "group": "kofua.app.revanced",
          "module": "brut.j.util",
          "version": {
            "requires": "2.12.0.1"
          }
        },
        {
          "group": "kofua.app.revanced",
          "module": "brut.j.dir",
          "version": {
            "requires": "2.12.0.1"
          }
        },
        {
          "group": "kofua.app.revanced",
          "module": "brut.j.xml",
          "version": {
            "requires": "2.12.0.1"
          }
        },
        {
          "group": "kofua.app.revanced",
          "module": "brut.j.yaml",
          "version": {
            "requires": "2.12.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "apktool-lib-2.12.0.1.jar",
          "url": "apktool-lib-2.12.0.1.jar",
          "size": 34978779,
          "sha512": "a94bcdf55c44f8669fb72c73438d8045fb94976adda88c3413f234cd3d03d9a10303a3e9d28fa07cd17bd812f84c6651386537e18b573136301b581e95bf2abe",
          "sha256": "dc850340dc65cb1d213e470225bb64e60ff9c8cd59035d481809036b048eb87f",
          "sha1": "2bf0f1a36647822f6d6e6956b6428c4060a41792",
          "md5": "d25f010b6360c11f5bf20435f3696f97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apktool-lib-2.12.0.1-javadoc.jar",
          "url": "apktool-lib-2.12.0.1-javadoc.jar",
          "size": 454851,
          "sha512": "fefa6de014f0d76e1aeb445d78f449f9e35a95239bb8b052e3027bc7d1b55e0db5b9c402c68e5477ca156c40e38f65a3664899b520da85a3e038ad900cd4414c",
          "sha256": "25abc5b20a3e1e7f82260f74a330fc4bbff8506d135cf6516ba297a7619f531b",
          "sha1": "55b7e5559e4e3d5c2d7318633e7d34e8a8928638",
          "md5": "9b01cc8b5cebe536f7f675e5ced95418"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "apktool-lib-2.12.0.1-sources.jar",
          "url": "apktool-lib-2.12.0.1-sources.jar",
          "size": 34926528,
          "sha512": "6ce30fd537d2dc669a374a7af38580867f425dbcb2a49b5a7f2b903fe69e4388f7d1dc23e1040919769a6384f04bc5bb89f05b87171ebf0673bbe55d320972af",
          "sha256": "f999fd9bfec7e45701783bbc4e21b6fd342a72e6a9a669c80cbb517a24db5786",
          "sha1": "d73ce07ca55db12eb0b41a537f89407e31d193a5",
          "md5": "9ad3c76fb70ebdb67e0715c828c3078c"
        }
      ]
    }
  ]
}
