{
  "formatVersion": "1.1",
  "component": {
    "group": "kofua.app.revanced",
    "module": "brut.j.util",
    "version": "2.12.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brut.j.util-2.12.0.1.jar",
          "url": "brut.j.util-2.12.0.1.jar",
          "size": 15143,
          "sha512": "d335467bc194597903d94e922c99c4dcb0ba8808c2f76e93d10f72e19eab62d4201081a1279a23fee85285d3bb4fe94bbd6f8b4e45110ea8e2e882116a17931d",
          "sha256": "00b84e6beff1c4a806f10a25556fcba4d53b96e509b844b4e5ba9b6f3e64e531",
          "sha1": "2fb2e6c38c7991a6dd6484710fd34a3027f3f917",
          "md5": "e9b54ad66add089237dcc155b1b6ac57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "kofua.app.revanced",
          "module": "brut.j.common",
          "version": {
            "requires": "2.12.0.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-jre"
          }
        }
      ],
      "files": [
        {
          "name": "brut.j.util-2.12.0.1.jar",
          "url": "brut.j.util-2.12.0.1.jar",
          "size": 15143,
          "sha512": "d335467bc194597903d94e922c99c4dcb0ba8808c2f76e93d10f72e19eab62d4201081a1279a23fee85285d3bb4fe94bbd6f8b4e45110ea8e2e882116a17931d",
          "sha256": "00b84e6beff1c4a806f10a25556fcba4d53b96e509b844b4e5ba9b6f3e64e531",
          "sha1": "2fb2e6c38c7991a6dd6484710fd34a3027f3f917",
          "md5": "e9b54ad66add089237dcc155b1b6ac57"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brut.j.util-2.12.0.1-javadoc.jar",
          "url": "brut.j.util-2.12.0.1-javadoc.jar",
          "size": 114654,
          "sha512": "116958249ebe9ddc050d995190bac54162b29d5fab8e7a7efc063f28f5df83439391743d7f991a752bd0d87119232c9a5af50178f50d9fabbbd04e317f9a221e",
          "sha256": "e926f4988675fb5b5407378cbec32d5d038b4b89f73ebbff4d23ffb17b11dadc",
          "sha1": "1792c28af11685a75e9041e693b0a72e13bc9348",
          "md5": "a5135cc4e9aa49428f23f6da3ce362e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brut.j.util-2.12.0.1-sources.jar",
          "url": "brut.j.util-2.12.0.1-sources.jar",
          "size": 10006,
          "sha512": "498cfed03d0678e97c98184cef425250e92fbe8997a168643f247673ce8b97d5c9cbc3060a0144c0177e723dbedbe697ced119ffa2cbd0019e3ada28e0d68f07",
          "sha256": "bee74603dde0243a6a495e2a9e73dbc0c5fc30f2f1be24c39fa6b84fb597208b",
          "sha1": "8315e68e26a9fb6225c9dec08d1731583a93d34c",
          "md5": "503be09e93d69e8bcdab4dfd06425cea"
        }
      ]
    }
  ]
}
