{
  "formatVersion": "1.1",
  "component": {
    "group": "kofua.app.revanced",
    "module": "brut.j.common",
    "version": "2.12.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brut.j.common-2.12.0.1.jar",
          "url": "brut.j.common-2.12.0.1.jar",
          "size": 2207,
          "sha512": "f46d556c3fc23829e2508e9267d3022177494b0e335fae2dad11ddc0f1df37fa12f18915ddd736e8dd14271cd51b3d04f8e4815cdcf6efb9c6182ab0c0632db6",
          "sha256": "844d801acf607e45e31db4cfaa2280296b5c4ffca31356c41dddf8dba4b30a8a",
          "sha1": "4771bba9768a0227bfee1d3a90af8cd1bf810516",
          "md5": "d257e8bc316d99b3078ae19f44ce62d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brut.j.common-2.12.0.1.jar",
          "url": "brut.j.common-2.12.0.1.jar",
          "size": 2207,
          "sha512": "f46d556c3fc23829e2508e9267d3022177494b0e335fae2dad11ddc0f1df37fa12f18915ddd736e8dd14271cd51b3d04f8e4815cdcf6efb9c6182ab0c0632db6",
          "sha256": "844d801acf607e45e31db4cfaa2280296b5c4ffca31356c41dddf8dba4b30a8a",
          "sha1": "4771bba9768a0227bfee1d3a90af8cd1bf810516",
          "md5": "d257e8bc316d99b3078ae19f44ce62d8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brut.j.common-2.12.0.1-javadoc.jar",
          "url": "brut.j.common-2.12.0.1-javadoc.jar",
          "size": 102515,
          "sha512": "e6153a353aa3c99a78e0ce8590089891648df3e80a526b9c43640998074e8bce3585ee39ee3cc3c2b32fc910a72b438f7f6997a82aac6a4507c1a144a495ae9d",
          "sha256": "37554a5767cd6498c086e89c46b5fc4e7ddeda74f0c7b62da329f00428e11190",
          "sha1": "d69a640bd84f47f2fd75ea9573ca0707570445b9",
          "md5": "bd5a420941e920c60aef0819464ea4a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brut.j.common-2.12.0.1-sources.jar",
          "url": "brut.j.common-2.12.0.1-sources.jar",
          "size": 3140,
          "sha512": "82c9ffda9c8d4cf0356c762d82623b724d94d5bef5bd983615a12a7cce27d8e58e1cf1af8debd0f3718f1bacbb9caf6565c245e79c6c7bc1200a67333e8d3a3d",
          "sha256": "4ff8347348b42148d69c3876d673764475d6525b09fd2475e8c1bacc33608831",
          "sha1": "388d77ce2560629c092faf36a18953171f70a1c9",
          "md5": "14473de01a90bb008a836ae3bf75fb99"
        }
      ]
    }
  ]
}
