{
  "formatVersion": "1.1",
  "component": {
    "group": "app.revanced",
    "module": "brut.j.dir",
    "version": "2.10.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brut.j.dir-2.10.1.1.jar",
          "url": "brut.j.dir-2.10.1.1.jar",
          "size": 18374,
          "sha512": "0657db32d46f8cf3b21c39354004fb906ef73f275f81ad36a7fdca4f92c26ad8de3172b5c87b610bef02aac827a63201b7f90aad5e2b0bfd9a0d7e25e15ca8df",
          "sha256": "63d054d0cfc6913adad257f555efee1f1e94b72f0cb01bcc7a522afa2ef29496",
          "sha1": "946d573f26a42e03198dcaf8a61f1707a56f5e2a",
          "md5": "f9411efc86e1328a19b525ec3828c61f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "app.revanced",
          "module": "brut.j.common",
          "version": {
            "requires": "2.10.1.1"
          }
        },
        {
          "group": "app.revanced",
          "module": "brut.j.util",
          "version": {
            "requires": "2.10.1.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "brut.j.dir-2.10.1.1.jar",
          "url": "brut.j.dir-2.10.1.1.jar",
          "size": 18374,
          "sha512": "0657db32d46f8cf3b21c39354004fb906ef73f275f81ad36a7fdca4f92c26ad8de3172b5c87b610bef02aac827a63201b7f90aad5e2b0bfd9a0d7e25e15ca8df",
          "sha256": "63d054d0cfc6913adad257f555efee1f1e94b72f0cb01bcc7a522afa2ef29496",
          "sha1": "946d573f26a42e03198dcaf8a61f1707a56f5e2a",
          "md5": "f9411efc86e1328a19b525ec3828c61f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brut.j.dir-2.10.1.1-javadoc.jar",
          "url": "brut.j.dir-2.10.1.1-javadoc.jar",
          "size": 107352,
          "sha512": "9dc96e1c346a1a7c56c9199207d86c50a0f9736f553c35cb5e7d92919f5305c3d8c749ca8b4752ec34c756610699a041cb29173966ccac46ff468b7006f378c3",
          "sha256": "3b9e4600863c9879131963d39c5eef5d775d87c76e37f9d3f7f526b36aa1758f",
          "sha1": "640ed0727094dc732b564620f5ba9232c6a768c5",
          "md5": "52e54489c12f87e8422bcc10f5fc357a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brut.j.dir-2.10.1.1-sources.jar",
          "url": "brut.j.dir-2.10.1.1-sources.jar",
          "size": 12191,
          "sha512": "9304d204c86f85e24e39b4e4388de07f03254c26ca2b9a2c1f90e2efbb188ae33f6c3c868e4b6bb09ab11463b557231459d68c3630b1a315916410090308971e",
          "sha256": "508c12ab54f98d3e0db93aa6cce2de1754942fa70b097379ac9e856c25c8a5f1",
          "sha1": "07c42c8a0429d19a419292c28726e1ab88fdb41f",
          "md5": "c17c1ad88a0c4a9914b30652b3540c92"
        }
      ]
    }
  ]
}
