{
  "formatVersion": "1.1",
  "component": {
    "group": "app.morphe",
    "module": "morphe-patcher",
    "version": "1.0.0-dev.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "morphe-patcher-1.0.0-dev.1.jar",
          "url": "morphe-patcher-1.0.0-dev.1.jar",
          "size": 285986,
          "sha512": "6e38b889271484ab78daf94e0229e7dd3f682716ec7a2842115f966567fa8d7f01a4b0942f8c5cdb8051875217f4a73e7b9f1cd2cfc25bd99953f9950495b476",
          "sha256": "4abc3282d8b0291f23956b6818e157ffe119ee4a44a4ddadaf18f8aef2320361",
          "sha1": "6b7a94382ae8e6f9a3ad4dde9090cdf3b38bb339",
          "md5": "1544de9d3220c6588a183b861faf2222"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.revanced",
          "module": "apktool-lib",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "app.revanced",
          "module": "multidexlib2",
          "version": {
            "requires": "3.0.3.r3"
          }
        },
        {
          "group": "com.android.tools.smali",
          "module": "smali",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "xpp3",
          "module": "xpp3",
          "version": {
            "requires": "1.1.4c"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "morphe-patcher-1.0.0-dev.1.jar",
          "url": "morphe-patcher-1.0.0-dev.1.jar",
          "size": 285986,
          "sha512": "6e38b889271484ab78daf94e0229e7dd3f682716ec7a2842115f966567fa8d7f01a4b0942f8c5cdb8051875217f4a73e7b9f1cd2cfc25bd99953f9950495b476",
          "sha256": "4abc3282d8b0291f23956b6818e157ffe119ee4a44a4ddadaf18f8aef2320361",
          "sha1": "6b7a94382ae8e6f9a3ad4dde9090cdf3b38bb339",
          "md5": "1544de9d3220c6588a183b861faf2222"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "morphe-patcher-1.0.0-dev.1-sources.jar",
          "url": "morphe-patcher-1.0.0-dev.1-sources.jar",
          "size": 57177,
          "sha512": "4c5096473a2556b0219eae8d423cfebfc452c54478582b067b45fbafe57c051d15ba27b494577f3f711017107fcd00cb2abb1cbdcee3d58f0e41d77e7a38439a",
          "sha256": "8ae4ebb8c133150a1af83e56c3ab7a8724fb72a72cfb9560c07dab5c62436f9e",
          "sha1": "ae220f38b83fc203c4963c601c7c30c924b2cda3",
          "md5": "24493c465aee4f61706e79eb6a943a31"
        }
      ]
    }
  ]
}
