{
  "formatVersion": "1.1",
  "component": {
    "group": "app.revanced",
    "module": "multidexlib2",
    "version": "3.0.3.r3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.tools.smali",
          "module": "smali-dexlib2",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.2-jre"
          }
        }
      ],
      "files": [
        {
          "name": "multidexlib2-3.0.3.r3.jar",
          "url": "multidexlib2-3.0.3.r3.jar",
          "size": 40162,
          "sha512": "851c2ea6a088a6bdb78e8ae0a07898e176396bd6238ba5d9b7820e98d6346d39a932d9b153061b283cc1b5aefd807c2cf40a361c4e5e71ee9ded1ecd6921ed30",
          "sha256": "70b2d7d14b78e82885c5ca908119821f663bd5cf4ec93785e98e148c08419cbc",
          "sha1": "d7e1e67158cccbf4fcdd25ecfbf9c4302cde466d",
          "md5": "8d170ca2febd40a15c87a8e999a41b99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.smali",
          "module": "smali-dexlib2",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.2-jre"
          }
        }
      ],
      "files": [
        {
          "name": "multidexlib2-3.0.3.r3.jar",
          "url": "multidexlib2-3.0.3.r3.jar",
          "size": 40162,
          "sha512": "851c2ea6a088a6bdb78e8ae0a07898e176396bd6238ba5d9b7820e98d6346d39a932d9b153061b283cc1b5aefd807c2cf40a361c4e5e71ee9ded1ecd6921ed30",
          "sha256": "70b2d7d14b78e82885c5ca908119821f663bd5cf4ec93785e98e148c08419cbc",
          "sha1": "d7e1e67158cccbf4fcdd25ecfbf9c4302cde466d",
          "md5": "8d170ca2febd40a15c87a8e999a41b99"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multidexlib2-3.0.3.r3-javadoc.jar",
          "url": "multidexlib2-3.0.3.r3-javadoc.jar",
          "size": 160546,
          "sha512": "5aa2f1e76cf8fe55d7b6ecf99309e7824396e812d9a4a0a4a08c9830c73fcd2580b1adbe054b629076368f2306a1c41d569623138d183d18bff88675cce4df3a",
          "sha256": "e5f77fc128e222bb3569939dbf227625e039e653b7b128144c3fdcfadeaf30d7",
          "sha1": "0cf4fd1fa2c57c16868c8ea1b26c0e77ab22ff59",
          "md5": "4ab2e3d8f811b33c68c571a657521a10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multidexlib2-3.0.3.r3-sources.jar",
          "url": "multidexlib2-3.0.3.r3-sources.jar",
          "size": 18637,
          "sha512": "2775a99adcef69cceafcad9d23912e82b745801690d06b73e7d51addeab733a35f7fd918668029aea8481aa05148fb5dd2b835d9e3878dc84957c9c7303b9eb5",
          "sha256": "47a422f9567f12c52f4252c7fc8b03016e5f4fac9931f28771ad98a94881f913",
          "sha1": "6ccbc2fa79db3ee7e5855b8ca3a7189215f0e094",
          "md5": "2cda6c9b13dbd9c30a430ee7492c55dc"
        }
      ]
    }
  ]
}
